############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Data Recovery"
url = "data-recovery-services/"
weight = 4

[[main]]
name = "Data Security"
url = "data-security/"
weight = 5

[[main]]
name = "Digital Forensics"
url = "data-forensics/"
weight = 7
  
[[main]]
name = "Why Choose Us"
url = "why-choose-us/"
weight = 15

[[main]]
name = "Support"
url = "support/"
weight = 20


[[main]]
name = "Contact Us"
url = "contact-us/"
weight = 25

# top menus
[[topmenu]]
name = "careers"
url = "/why-choose-us/company/careers/"
weight = 1
[[topmenu]]
name = "Our Credentials"
url = "/why-choose-us/company/our-credentials/"
weight = 2
[[topmenu]]
name = "Blog"
url = "/blog/"
weight = 3

# footer menus

#contact us
[[services]]
  name = "Start My Recovery"
  url = "/start-my-recovery/"
  weight = 2
[[services]]
  name = "Company"
  url = "/why-choose-us/company//"
  weight = 3
[[services]]
  name = "Resource Library"
  url = "/support/resource-library/"
  weight = 4
[[services]]
  name = "Locations"
  url = "/contact-us/#locations"
  weight = 5

#important links
[[important_links]]
  name = "Data Recovery Home"
  url = "/data-recovery-services/"
  weight = 1
[[important_links]]
  name = "eDiscovery Services"
  url = "/data-forensics/ediscovery-services/"
  weight = 2
[[important_links]]
  name = "ESI Forensics"
  url = "/data-forensics/esi-forensics/"
  weight = 3
[[important_links]]
  name = "Data Security"
  url = "/data-security/"
  weight = 4
