#################### default parameters ################################
logo = "images/bounceback-logo.png"
logo_text = "BounceBack Data Recovery"
description = "BounceBack Data Recovery delivers secure, professional data recovery services for hard drives, servers, medical records, and mobile devices, ensuring privacy, reliability, and peace of mind."
author = "BounceBack Data Recovery"
image = "/images//data-recovery.jpg" # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "BounceBack Data Recovery provides trusted, secure data recovery for hard drives, servers, medical records, and phones, ensuring fast, reliable service and complete data protection."


# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
phone = ["314-690-3009","1-636-333-0030"]
email = ["info@bouncebackdata.com"]
opening_hours = "24/7"

# address info for contact page
[address_info]
phone_one = "314-690-3009"
phone_two = "1-636-333-0030"
location = "151 New York Ave, Hartford, CT 87329 United States"

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100


# Navigation button
[primary_button]
enable = true
label = "Recover Now"
link = "/start-my-recovery/"

[privacy_button]
label = "Privacy Policy"
link = "/support/privacy-policy-3/"


############################# contact page social site ########################
[[contact]]
title = "facebook"
icon = "images/facebook-green.svg"
link = "https://www.facebook.com/pages/BounceBack-Data-Recovery-Inc/209793635724253?sk=wall"

[[contact]]
title = "linkedin"
icon = "images/linkedin-green.svg"
link = ""

[[contact]]
title = "twitter"
icon = "images/twitter-green.svg"
link = "https://x.com/BounceBack1"

[[contact]]
title = "youtube"
icon = "images/youtube-green.svg"
link = ""




############################# social site ########################
[[social]]
title = "facebook"
icon = "images/facebook.svg"
link = "https://www.facebook.com/pages/BounceBack-Data-Recovery-Inc/209793635724253?sk=wall"

[[social]]
title = "twitter"
icon = "images/twitter.svg"
link = "https://x.com/BounceBack1"


