# collections_config:

#   pages:
#     _enabled_editors:
#       - visual
#       - content
#   other-pages:
#     _enabled_editors:
#       - visual
#       - content

#   all-doctors-pages:
#     name: All Doctors Pages
#     path: content/english/doctors
#     schemas:
#       default: &ref_1
#         path: .cloudcannon/schemas/doctor-details-page.md
#         name: doctor-details-page
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - content
#         _inputs:
#           $.services:
#             label: Clinics/Services
#           $.title_image:
#             label: Image
#           $.details:
#             label: Designation
#           $.location:
#             label: Branch Name
#   doctors-landing-page:
#     name: Doctors Landing Page
#     path: content/english/doctors
#     filter:
#       exclude:
#         - Dr. Abdalla Elagha.md
#         - Dr. Abdallah Osama.md
#         - Dr. Abdel Maguid Ramzy.md
#         - Dr. Adel AbdelAziz.md
#         - Dr. Adel El-Nazer.md
#         - Dr. Adly Sbour.md
#         - Dr. Ahel Badawy.md
#         - Dr. Ahmad Abdelhady.md
#         - Dr. Ahmad Fathy.md
#         - Dr. Ahmed Abdel Ghani.md
#         - Dr. Ahmed Abdel Latif.md
#         - Dr. Ahmed Abdelaziz Marei.md
#         - Dr. Ahmed Abo Zamel.md
#         - Dr. Ahmed Aziz.md
#         - Dr. Ahmed El Ray.md
#         - Dr. Ahmed El-Shazly.md
#         - Dr. Ahmed Eldamaty.md
#         - Dr. Ahmed Gharib.md
#         - Dr. Ahmed Magdy.md
#         - Dr. Ahmed Radwan.md
#         - Dr. Ahmed Reda Awadein.md
#         - Dr. Ahmed Saeed Al-Shall.md
#         - Dr. Ahmed Shoukry.md
#         - Dr. Ahmed Sobhy.md
#         - Dr. Akram Abdul Rahman Mohamed.md
#         - Dr. Ali Abdel Wahab.md
#         - Dr. Aly El Mofty.md
#         - Dr. Amira El-Shennawy.md
#         - Dr. Amr Abdelrahem.md
#         - Dr. Amr El Badrawy.md
#         - Dr. Amr El Meliegy.md
#         - Dr. Amr Hassan Mostafa.md
#         - Dr. Amr Massoud.md
#         - Dr. Amr Sharaf.md
#         - Dr. Antoine Halepian.md
#         - Dr. Ashraf Amin.md
#         - Dr. Ashraf Fayek.md
#         - Dr. Ayman Abdel Moniem.md
#         - Dr. Ayman Aly Elsallamy.md
#         - Dr. Ayman Shawky.md
#         - Dr. Cherif Zaazou.md
#         - Dr. Cherifa Sharaf.md
#         - Dr. Dalia Abdel Ghany.md
#         - Dr. Dina Mohamed.md
#         - Dr. Ehab Eid.md
#         - Dr. Ehab El Sharkawy.md
#         - Dr. Ehab Soliman.md
#         - Dr. Emad Hamada.md
#         - Dr. Emad Helmy.md
#         - Dr. Eman Sorour.md
#         - Dr. Eman Zein El-Abedeen.md
#         - Dr. Emmanuel Fares.md
#         - Dr. Fatema Alzahraa Saad.md
#         - Dr. Fathy Khodair.md
#         - Dr. Fouad El Nawawy.md
#         - Dr. Hala Mufeed.md
#         - Dr. Hanna Aboulghar.md
#         - Dr. Hany Aref.md
#         - Dr. Hany Edward.md
#         - Dr. Hany Ragy.md
#         - Dr. Hasan El-Hefnawy.md
#         - Dr. Hassan El Gamal.md
#         - Dr. Hassan El Hoshy.md
#         - Dr. Heba Gawdat.md
#         - Dr. Heba Sedrak.md
#         - Dr. Hesham Saleh.md
#         - Dr. Hisham Bassiouny.md
#         - Dr. Hisham El Kattan.md
#         - Dr. Hisham Shokeir.md
#         - Dr. Hossam Badrawi.md
#         - Dr. Hossam El Husseiny.md
#         - Dr. Ihab El Borai.md
#         - Dr. Jehan Sadek.md
#         - Dr. Josette Abdalla.md
#         - Dr. Kamal Maurice Hanna.md
#         - Dr. Karim Mourice.md
#         - Dr. Khadiga Abdel Kader.md
#         - Dr. Khaled El Hadidi.md
#         - Dr. Khaled El Hoshy.md
#         - Dr. Khaled El-Menebbawy.md
#         - Dr. Khaled Youssef.md
#         - Dr. Laila Saleh Abouda.md
#         - Dr. Liu Ruiyu.md
#         - Dr. Magdy Tawakol.md
#         - Dr. Maged Zekri.md
#         - Dr. Maha Abdelhady.md
#         - Dr. Maha Assem.md
#         - Dr. Maha Youssef Rakha.md
#         - Dr. Mahmoud Afifi.md
#         - Dr. Mahmoud Moheb.md
#         - Dr. Mai Atef.md
#         - Dr. Manal Hosny.md
#         - Dr. Manal Salah.md
#         - Dr. Marwan Yousry.md
#         - Dr. Medhat Abd Elsalam.md
#         - Dr. Mervat Mattar.md
#         - Dr. Moataza Bashir.md
#         - Dr. Mohamed A. Tawfik.md
#         - Dr. Mohamed Abdel-Azem.md
#         - Dr. Mohamed Abdelbary.md
#         - Dr. Mohamed El Gammal.md
#         - Dr. Mohamed El Khashab.md
#         - Dr. Mohamed El Nokaly.md
#         - Dr. Mohamed El Ramly.md
#         - Dr. Mohamed El-Barbary.md
#         - Dr. Mohamed El-Malt.md
#         - Dr. Mohamed El-Toukhy.md
#         - Dr. Mohamed Hakky.md
#         - Dr. Mohamed Hassan Daoud.md
#         - Dr. Mohamed Hosny.md
#         - Dr. Mohamed Kotb.md
#         - Dr. Mohamed Mahrous.md
#         - Dr. Mohamed Mokhles.md
#         - Dr. Mohamed Refaat.md
#         - Dr. Mohamed Refaay.md
#         - Dr. Mohamed Saher Hashem.md
#         - Dr. Mohamed Said.md
#         - Dr. Mohamed Talaat.md
#         - Dr. Mohamed Tarek El Far.md
#         - Dr. Mohamed Zaazou.md
#         - Dr. Mohammed Abdel Kader.md
#         - Dr. Mona Abdel Razek.md
#         - Dr. Mona El Fangary.md
#         - Dr. Mona El-Akkad.md
#         - Dr. Mona Roshdy.md
#         - Dr. Mostafa Kamal El Areeny.md
#         - Dr. Mostafa Sheba.md
#         - Dr. Moustafa Gamal Eldin.md
#         - Dr. Nabil Fawzy.md
#         - Dr. Nadia Badrawi.md
#         - Dr. Nadia Mostafa.md
#         - Dr. Nehal El Ghobashy.md
#         - Dr. Nevin Mamdouh.md
#         - Dr. Noha Sabry.md
#         - Dr. Omar El Falaky.md
#         - Dr. Omneya Helal.md
#         - Dr. Radwa Bakry.md
#         - Dr. Randa Ragy.md
#         - Dr. Rasha Ammar.md
#         - Dr. Rehab Sobhy.md
#         - Dr. Reham Faheem Aziz.md
#         - Dr. Salah El Shazly.md
#         - Dr. Salma El Houchi.md
#         - Dr. Salma Hamed Khalil.md
#         - Dr. Samah Aboul Gheit.md
#         - Dr. Samar El-Tahlawi.md
#         - Dr. Samuel Makar.md
#         - Dr. Shehab Soliman.md
#         - Dr. Shereen Abdelghaffar.md
#         - Dr. Shereen Aboul Naga.md
#         - Dr. Shereen Farouk Goma.md
#         - Dr. Sherif El Hawary.md
#         - Dr. Sherif Magdy Amin.md
#         - Dr. Sherif Naguib.md
#         - Dr. Sherif Omer Elkerdawi.md
#         - Dr. Sobhi El Masry.md
#         - Dr. Soliman Mohamed Soliman.md
#         - Dr. Tamer Gawdat.md
#         - Dr. Tarek Abdel Samei.md
#         - Dr. Tarek Anis.md
#         - Dr. Tarek Elbeltagi.md
#         - Dr. Tarek Zaki.md
#         - Dr. Tawfik Gozailan.md
#         - Dr. Wael Fathy.md
#         - Dr. Wafaa EL-Aroussy.md
#         - Dr. Walaa El Ashry.md
#         - Dr. Waleed El Sorougi.md
#         - Dr. Wedad Mostafa.md
#         - Dr. Wessam Roshdy.md
#         - Dr. Yehia Safwat.md
#         - Dr. Zoheir El Hoshy.md
#         - dr.ahmed-el-sharkawy.md
#         - dr.ahmed-saed-zaki.md
#         - dr.alaa-balbaa.md
#         - dr.hatem-el-khabiry.md
#         - dr.marwa-sabry.md
#         - dr.shadi-abdel-salam.md
#         - Mrs. Dina Sid Ahmed.md
#         - Mrs. Maha Abou Taleb.md
#         - Mrs. Nadja Hathout.md
#         - Prof ElZaher Hassan ElZaher.md
#         - prof.sayed-oraby.md
#   clinics:
#     name: Clinics
#     path: content/english/clinics
#     schemas:
#       default:
#         path: .cloudcannon/schemas/clinics-details-page.md
#         name: clinics-details-page
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - content
#         _inputs:
#           $.layout:
#             hidden: true
#   services:
#     name: Services
#     path: content/english/services
#     schemas:
#       default:
#         path: .cloudcannon/schemas/services-page.md
#         name: services-page
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - content
#   health-tips-posts:
#     name: Health Tips Posts
#     path: content/english/health-tips
#     schemas:
#       default: &ref_0
#         path: .cloudcannon/schemas/blog-post-template.md
#         name: blog post template
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - content
#         _inputs:
#           $.layout:
#             hidden: true
#   events:
#     name: Events
#     path: content/english/events
#     schemas:
#       default: *ref_0
#   news:
#     name: News
#     path: content/english/news
#     schemas:
#       default: *ref_0
#   careers:
#     name: Careers
#     path: content/english/careers
#     schemas:
#       default: *ref_0
#   pages:
#     name: Pages
#     path: content/english/pages
#     schemas:
#       about-us-page:
#         path: .cloudcannon/schemas/about-us-page.md
#         name: about-us-page
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - data
#         _inputs:
#           $.about_mission.list:
#             type: array
#       contact_us-page: &ref_2
#         path: .cloudcannon/schemas/contact_us-page.md
#         name: contact_us-page
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - data
#         _inputs:
#           $.google_map.locations:
#             type: array
#             options:
#               structures: _structures.locations
#       service-enquiry:
#         path: .cloudcannon/schemas/service-enquiry.md
#         name: service-enquiry
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - data
#       new-service-page: &ref_3
#         path: .cloudcannon/schemas/new-service-page.md
#         name: new-service-page
#         remove_extra_inputs: false
#         hide_extra_inputs: true
#         _enabled_editors:
#           - content
#   config:
#     name: Config
#     path: config
#   default_hugo_pages:
#     name: Pages
#     path: content/
#     schemas:
#       doctor-details-page: *ref_1
#       contact_us-page: *ref_2
#       new-service-page: *ref_3
# collection_groups:
#   - heading: Arabic Content
#     collections:
#       - all-doctors-pages
#       - doctors-landing-page
#       - clinics
#       - services
#       - health-tips-posts
#       - events
#       - news
#       - careers
#       - pages
#   - heading: English Content
#     collections:
#       - all-doctors-pages
#       - doctors-landing-page
#       - clinics
#       - services
#       - health-tips-posts
#       - events
#       - news
#       - careers
#       - pages
#   - heading: Configuration
#     collections:
#       - config
paths:
  static: assets
  uploads: assets/images
_structures:
  locations:
    values:
      - value:
          heading: ''
          address: ''
          mapURL: ''
          co_oridinate:
            lat: null
            lng: null
          telephone: []
          mobile: []
        _inputs:
          mapURL:
            type: textarea
          co_oridinate.lat:
            type: number
          co_oridinate.lng:
            type: number
          telephone:
            type: array
          mobile:
            type: array
  slide_items:
    values:
      - value:
          heading: ''
          schedule: ''
          button: ''
          button_url: ''
  slider:
    values:
      - value:
          cards: []
        _inputs:
          cards:
            type: array
            options:
              structures: _structures.cards
  cards:
    values:
      - value:
          image: null
          image_description: ''
          heading: ''
          text: ''
          url: ''
_inputs:
  template:
    hidden: true
  layout:
    hidden: true
  services:
    type: text
  clinics: 
    type: array
  clinics[*]:
    type: text
  text: 
    type: markdown
