paths:
  static: assets
  uploads: assets/images
collections_config:
  pages:
    path: content
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: content/blog
    glob:
      - '!_index.md'
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data_forensics:
    path: content/data-forensics
    glob:
      - '!_index.md'
    icon: data_check
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data_recovery_services:
    path: content/data-recovery-services
    glob:
      - '!_index.md'
    icon: home_repair_service
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  other_pages:
    path: content/other-pages
    glob:
      - '!_index.md'
    icon: other_houses
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  support:
    path: content/support
    glob:
      - '!_index.md'
    icon: support
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  why_choose_us:
    path: content/why-choose-us
    glob:
      - '!_index.md'
    icon: other_houses
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Asia/Dhaka
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
